// Cấu hình tất cả section của admin: sidebar nav + CRUD config
// icon: path bên trong <svg viewBox="0 0 24 24" stroke="currentColor">

const truncate = (s, n = 50) => (s && s.length > n ? s.slice(0, n) + '…' : s || '')

export const sections = [
  {
    id: 'products',
    label: 'Sản phẩm',
    table: 'products',
    title: 'Sản phẩm — Bàn bi-a',
    icon: <path d="M3 7h18v10H3zM3 11h18M8 7v10" />,
    columns: [
      { key: 'name', label: 'Tên' },
      { key: 'code', label: 'Mã' },
      { key: 'price', label: 'Giá' },
      { key: 'badge', label: 'Nhãn' },
    ],
    fields: [
      { key: 'name', label: 'Tên sản phẩm', type: 'text', required: true },
      { key: 'code', label: 'Mã (VK25)', type: 'text', required: true },
      { key: 'badge', label: 'Nhãn (Cao cấp nhất)', type: 'text' },
      { key: 'price', label: 'Giá', type: 'text' },
      { key: 'old_price', label: 'Giá cũ', type: 'text' },
      { key: 'frame', label: 'Khung', type: 'text', full: true },
      {
        key: 'specs',
        label: 'Thông số',
        type: 'array',
        full: true,
        rows: 4,
        hint: 'Mỗi dòng là một thông số.',
      },
      { key: 'size', label: 'Kích thước', type: 'textarea', full: true, rows: 2 },
      { key: 'image', label: 'URL ảnh', type: 'text', full: true },
    ],
  },
  {
    id: 'services',
    label: 'Dịch vụ',
    table: 'services',
    title: 'Dịch vụ',
    icon: <path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.6 2.6-2.4-.6-.6-2.4 2.6-2.6z" />,
    columns: [
      { key: 'title', label: 'Tiêu đề' },
      { key: 'icon', label: 'Icon' },
      { key: 'description', label: 'Mô tả', render: (r) => truncate(r.description, 60) },
    ],
    fields: [
      {
        key: 'icon',
        label: 'Icon',
        type: 'select',
        options: [
          { value: 'design', label: 'design (thiết kế)' },
          { value: 'cloth', label: 'cloth (vải/nỉ)' },
          { value: 'wrench', label: 'wrench (bảo trì)' },
          { value: 'truck', label: 'truck (vận chuyển)' },
        ],
      },
      { key: 'title', label: 'Tiêu đề', type: 'text', required: true, full: true },
      { key: 'description', label: 'Mô tả', type: 'textarea', full: true, rows: 3 },
    ],
  },
  {
    id: 'portfolio',
    label: 'Dự án (CLB)',
    table: 'portfolio',
    title: 'Dự án — CLB đã setup',
    icon: <path d="M3 21h18M5 21V7l8-4 8 4v14M9 9h.01M9 13h.01M9 17h.01" />,
    columns: [
      { key: 'name', label: 'Tên CLB' },
      { key: 'location', label: 'Địa điểm' },
      { key: 'tables', label: 'Số bàn' },
    ],
    fields: [
      { key: 'name', label: 'Tên CLB', type: 'text', required: true },
      { key: 'tables', label: 'Số bàn', type: 'number' },
      { key: 'location', label: 'Địa điểm', type: 'text', full: true },
      { key: 'img', label: 'URL ảnh', type: 'text', full: true },
    ],
  },
  {
    id: 'team',
    label: 'VĐV',
    table: 'pro_team',
    title: 'Đội ngũ VĐV & cố vấn',
    icon: <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0 .01M23 21v-2a4 4 0 0 0-3-3.87" />,
    columns: [
      { key: 'name', label: 'Tên' },
      { key: 'role', label: 'Vai trò' },
      { key: 'note', label: 'Ghi chú', render: (r) => truncate(r.note, 60) },
    ],
    fields: [
      { key: 'name', label: 'Tên', type: 'text', required: true },
      { key: 'role', label: 'Vai trò', type: 'text' },
      { key: 'note', label: 'Ghi chú', type: 'textarea', full: true, rows: 2 },
    ],
  },
  {
    id: 'testimonials',
    label: 'Cảm nhận',
    table: 'testimonials',
    title: 'Cảm nhận khách hàng',
    icon: <path d="M12 2l3 6.3 6.9 1-5 4.9 1.2 6.8L12 17.8 5.9 21l1.2-6.8-5-4.9 6.9-1z" />,
    columns: [
      { key: 'name', label: 'Tên' },
      { key: 'place', label: 'Nơi' },
      { key: 'rating', label: 'Sao', render: (r) => '⭐'.repeat(r.rating || 0) },
      { key: 'text', label: 'Nội dung', render: (r) => truncate(r.text, 50) },
    ],
    fields: [
      { key: 'name', label: 'Tên', type: 'text', required: true },
      { key: 'place', label: 'Nơi / CLB', type: 'text' },
      {
        key: 'rating',
        label: 'Đánh giá',
        type: 'select',
        options: [
          { value: '5', label: '⭐⭐⭐⭐⭐ (5)' },
          { value: '4', label: '⭐⭐⭐⭐ (4)' },
          { value: '3', label: '⭐⭐⭐ (3)' },
        ],
      },
      { key: 'text', label: 'Nội dung', type: 'textarea', full: true, rows: 3, required: true },
    ],
  },
  {
    id: 'club',
    label: 'Câu lạc bộ',
    table: 'club_posts',
    title: 'Bài viết Câu lạc bộ',
    icon: <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M4 19.5A2.5 2.5 0 0 0 6.5 22H20V2H6.5A2.5 2.5 0 0 0 4 4.5z" />,
    columns: [
      { key: 'title', label: 'Tiêu đề' },
      { key: 'cat', label: 'Danh mục' },
      { key: 'date', label: 'Ngày' },
    ],
    fields: [
      { key: 'title', label: 'Tiêu đề', type: 'text', required: true, full: true },
      { key: 'slug', label: 'Slug (chon-vai-ban)', type: 'text', required: true },
      { key: 'cat', label: 'Danh mục', type: 'text' },
      { key: 'date', label: 'Ngày (12/06/2026)', type: 'text' },
      { key: 'image', label: 'URL ảnh', type: 'text', full: true },
      { key: 'intro', label: 'Đoạn mở đầu', type: 'textarea', full: true, rows: 3 },
      {
        key: 'points',
        label: 'Các điểm chính',
        type: 'points',
        full: true,
        rows: 8,
        hint: 'Mỗi điểm: dòng 1 = tiêu đề, dòng 2 = mô tả. Ngăn cách các điểm bằng một dòng "---".',
      },
    ],
  },
  {
    id: 'partners',
    label: 'Đối tác',
    table: 'partners',
    title: 'Đối tác / Thương hiệu',
    icon: <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0 .01M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" />,
    columns: [{ key: 'name', label: 'Tên đối tác' }],
    fields: [{ key: 'name', label: 'Tên đối tác', type: 'text', required: true, full: true }],
  },
  {
    id: 'brand',
    label: 'Thương hiệu',
    table: 'brand_info',
    title: 'Thông tin thương hiệu',
    singleton: true,
    icon: <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82zM7 7h.01" />,
    fields: [
      { key: 'name', label: 'Tên thương hiệu', type: 'text' },
      { key: 'slogan', label: 'Slogan', type: 'text' },
      { key: 'tagline', label: 'Tagline', type: 'textarea', full: true, rows: 2 },
      { key: 'address', label: 'Địa chỉ', type: 'text', full: true },
      { key: 'phone_sales', label: 'SĐT kinh doanh', type: 'text' },
      { key: 'phone_tech', label: 'SĐT kỹ thuật', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'zalo', label: 'Zalo', type: 'text' },
      { key: 'facebook', label: 'Facebook URL', type: 'text', full: true },
    ],
  },
]
